name: Publish new dev version to pub

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish new dev version to pub

    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install dependencies âš™ï¸
        run: dart pub get

      - name: Generate ğŸ”§
        run: dart run tool/ci.dart bump-dev-version

      - name: Deploy ğŸš€
        run: dart run tool/ci.dart push-new-version
